kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: skanmotovrig
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: SKANMOTOVRIG_ENDPOINTS_DOKARKIV_URL
      value: {{ SKANMOTOVRIG_ENDPOINTS_DOKARKIV_URL }}
    - name: SKANMOTOVRIG_ENDPOINTS_DOKARKIV_SCOPE
      value: {{ SKANMOTOVRIG_ENDPOINTS_DOKARKIV_SCOPE }}
    - name: SKANMOTOVRIG_JIRA_URL
      value: {{ SKANMOTOVRIG_JIRA_URL }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 6250Mi
    requests:
      memory: 5000Mi
  azure:
    application:
      enabled: true
  webproxy: true
  filesFrom:
    - mountPath: /var/run/secrets/nais.io/skanmotovrig
      secret: {{ SKANMOTOVRIG_SECRET }}
  envFrom:
    - secret: {{ SKANMOTOVRIG_SECRET }}
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
